services:
  - type: web
    name: ai-workflow-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # IMPORTANT: GROQ_API_KEY must be set manually in Render dashboard
      # Go to your service > Environment tab > Add GROQ_API_KEY
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
